# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UI_Serial.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets
import re

class SmartHexTextEdit(QtWidgets.QTextEdit):
    """支持hex数据智能换行的文本编辑器"""
    
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.hex_mode = False
        
    def set_hex_mode(self, enabled):
        """设置是否为hex模式"""
        self.hex_mode = enabled
        
    def insertFromMimeData(self, source):
        text = source.text() if source and source.hasText() else ""
        if not text:
            return
        if self.hex_mode:
            text = self._process_hex_text(text)
        self.textCursor().insertText(text)
            
    def keyPressEvent(self, event):
        """重写按键事件，处理hex模式下的输入"""
        if self.hex_mode and event.key() == QtCore.Qt.Key_Return:
            # 在hex模式下按回车时，检查当前行是否会分割字节
            cursor = self.textCursor()
            current_line = cursor.block().text()
            
            # 如果当前行的hex字符数为奇数，添加一个空格
            hex_chars = re.sub(r'[^0-9A-Fa-f]', '', current_line)
            if len(hex_chars) % 2 == 1:
                cursor.insertText(' ')
                
        super().keyPressEvent(event)
        
    def _process_hex_text(self, text):
        """处理hex文本，确保字节完整性"""
        if not self.hex_mode:
            return text
            
        # 移除所有非hex字符，然后重新格式化
        hex_chars = re.sub(r'[^0-9A-Fa-f]', '', text)
        
        # 每两个字符组成一个字节，用空格分隔
        formatted_hex = ' '.join([hex_chars[i:i+2] for i in range(0, len(hex_chars), 2)])
        
        return formatted_hex


class Ui_Kero_Serial(object):
    def setupUi(self, Kero_Serial):
        Kero_Serial.setObjectName("Kero_Serial")
        Kero_Serial.resize(1162, 1244)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Kero_Serial.sizePolicy().hasHeightForWidth())
        Kero_Serial.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        Kero_Serial.setFont(font)
        self.centralwidget = MineWidget(Kero_Serial)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        # 减少主布局的边距和间距
        self.gridLayout_2.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_2.setSpacing(2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.groupBox.setFont(font)
        # 取消边框显示，美化界面
        self.groupBox.setStyleSheet("QGroupBox { border: none; }")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        # 减少水平布局的边距和间距
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.top_splitter = QtWidgets.QSplitter(self.groupBox)
        splitter_size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        splitter_size_policy.setHorizontalStretch(0)
        splitter_size_policy.setVerticalStretch(0)
        splitter_size_policy.setHeightForWidth(self.top_splitter.sizePolicy().hasHeightForWidth())
        self.top_splitter.setSizePolicy(splitter_size_policy)
        self.top_splitter.setOrientation(QtCore.Qt.Horizontal)
        self.top_splitter.setChildrenCollapsible(False)
        self.top_splitter.setHandleWidth(6)
        self.top_splitter.setOpaqueResize(False)
        self.top_splitter.setObjectName("top_splitter")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.top_splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_2.sizePolicy().hasHeightForWidth())
        self.tabWidget_2.setSizePolicy(sizePolicy)
        self.tabWidget_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget_2.setTabsClosable(True)
        # 美化标签页显示，减少边框
        self.tabWidget_2.setStyleSheet("QTabWidget::pane { border: 1px solid #C0C0C0; }")
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.tab_3)
        # 减少标签页内布局的边距和间距
        self.gridLayout_15.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_15.setSpacing(2)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setTitle("")
        # 取消接收区域边框显示
        self.groupBox_6.setStyleSheet("QGroupBox { border: none; }")
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.textBrowserShow = MyTextBrowser(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowserShow.sizePolicy().hasHeightForWidth())
        self.textBrowserShow.setSizePolicy(sizePolicy)
        # 移除硬编码字体设置，允许用户自定义字体
        self.textBrowserShow.setStyleSheet("font: 10pt \"Consolas\";")
        self.textBrowserShow.setObjectName("textBrowserShow")
        self.horizontalLayout_3.addWidget(self.textBrowserShow)
        self.gridLayout_15.addWidget(self.groupBox_6, 0, 1, 1, 1)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.tab_4)
        # 减少Filter标签页布局的边距和间距
        self.gridLayout_13.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_13.setSpacing(2)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        # 减少垂直布局间距
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.FilterBrowser = MyTextBrowser(self.tab_4)
        self.FilterBrowser.setObjectName("FilterBrowser")
        # 确保FilterBrowser使用与textBrowserShow相同的字体样式
        self.FilterBrowser.setStyleSheet("font: 10pt \"Consolas\";")
        self.verticalLayout.addWidget(self.FilterBrowser)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        # 减少水平布局间距
        self.horizontalLayout_6.setSpacing(2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.Filter_Regexp = QtWidgets.QLineEdit(self.tab_4)
        self.Filter_Regexp.setFixedWidth(300)  # 设置固定宽度为300px
        self.Filter_Regexp.setObjectName("Filter_Regexp")
        self.horizontalLayout_6.addWidget(self.Filter_Regexp)
        
        # 添加区分大小写单选框
        self.CaseSensitiveCheckBox = QtWidgets.QCheckBox(self.tab_4)
        self.CaseSensitiveCheckBox.setObjectName("CaseSensitiveCheckBox")
        self.horizontalLayout_6.addWidget(self.CaseSensitiveCheckBox)
        
        # 添加反选模式单选框
        self.InvertModeCheckBox = QtWidgets.QCheckBox(self.tab_4)
        self.InvertModeCheckBox.setObjectName("InvertModeCheckBox")
        self.horizontalLayout_6.addWidget(self.InvertModeCheckBox)
        
        self.HistoryFilterButton = QtWidgets.QPushButton(self.tab_4)
        self.HistoryFilterButton.setMinimumSize(QtCore.QSize(75, 0))
        self.HistoryFilterButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.HistoryFilterButton.setObjectName("HistoryFilterButton")
        self.horizontalLayout_6.addWidget(self.HistoryFilterButton)
        self.horizontalLayout_6.addStretch()  # 添加弹性空间
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.gridLayout_13.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.horizontalLayout.addWidget(self.top_splitter)
        self.tabWidget_expand = QtWidgets.QTabWidget(self.top_splitter)
        self.tabWidget_expand.setObjectName("tabWidget_expand")
        
        # 创建多字符串tab页
        self.tab_multistring = QtWidgets.QWidget()
        self.tab_multistring.setObjectName("tab_multistring")
        
        # 创建滚动区域放在多字符串tab中
        self.scrollArea = QtWidgets.QScrollArea(self.tab_multistring)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)  # 删除边框线
        self.scrollArea.setMinimumWidth(400)  # 设置最小宽度避免横向滚动条
        self.scrollArea.setMinimumHeight(200)  # 设置最小高度确保列表内容显示
        self.scrollArea.setObjectName("scrollArea")
        
        # 为多字符串tab创建布局
        self.multistring_layout = QtWidgets.QVBoxLayout(self.tab_multistring)
        self.multistring_layout.setContentsMargins(0, 0, 0, 0)
        self.multistring_layout.addWidget(self.scrollArea)
        
        # 创建自定义按钮组
        self.groupBox_customs = QtWidgets.QGroupBox()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_customs.sizePolicy().hasHeightForWidth())
        self.groupBox_customs.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(False)
        font.setWeight(QtGui.QFont.Weight.Normal)
        self.groupBox_customs.setFont(font)
        self.groupBox_customs.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.groupBox_customs.setWhatsThis("")
        self.groupBox_customs.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_customs.setObjectName("groupBox_customs")
        
        # 设置垂直布局，包含顺序执行单选框和表单布局
        self.verticalLayout_customs = QtWidgets.QVBoxLayout(self.groupBox_customs)
        self.verticalLayout_customs.setObjectName("verticalLayout_customs")
        # 顶部两行间距增加5px，并移除边距
        self.verticalLayout_customs.setSpacing(5)
        self.verticalLayout_customs.setContentsMargins(0, 0, 0, 0)
        
        # 顶部控制布局：开始/导入/导出
        self.horizontalLayout_top_controls = QtWidgets.QHBoxLayout()
        self.horizontalLayout_top_controls.setObjectName("horizontalLayout_top_controls")
        # 将按钮间距在当前基础上增加10px
        try:
            current_spacing = self.horizontalLayout_top_controls.spacing()
            if current_spacing is None or current_spacing < 0:
                self.horizontalLayout_top_controls.setSpacing(10)
            else:
                self.horizontalLayout_top_controls.setSpacing(current_spacing + 10)
        except Exception:
            self.horizontalLayout_top_controls.setSpacing(10)

        # 创建开始按钮（默认“开始”，运行中会切换为“停止”）
        self.pushButton_stop_loop = QtWidgets.QPushButton(self.groupBox_customs)
        self.pushButton_stop_loop.setObjectName("pushButton_stop_loop")
        self.pushButton_stop_loop.setText("开始")
        self.pushButton_stop_loop.setMaximumWidth(60)

        # 添加导入/导出按钮（兼容 sscom51.ini）
        self.pushButton_import_sscom = QtWidgets.QPushButton(self.groupBox_customs)
        self.pushButton_import_sscom.setObjectName("pushButton_import_sscom")
        self.pushButton_import_sscom.setText("导入")
        self.pushButton_import_sscom.setToolTip("从 Gavin_com_multsrt.ini 导入多字符串配置")
        self.pushButton_import_sscom.setMaximumWidth(60)
        self.horizontalLayout_top_controls.addWidget(self.pushButton_import_sscom)

        self.pushButton_export_sscom = QtWidgets.QPushButton(self.groupBox_customs)
        self.pushButton_export_sscom.setObjectName("pushButton_export_sscom")
        self.pushButton_export_sscom.setText("导出")
        self.pushButton_export_sscom.setToolTip("导出当前多字符串配置为 Gavin_com_multsrt.ini")
        self.pushButton_export_sscom.setMaximumWidth(60)
        self.horizontalLayout_top_controls.addWidget(self.pushButton_export_sscom)

        # 顶部弹簧
        topSpacer = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_top_controls.addItem(topSpacer)

        # 添加顶部布局到垂直布局
        self.verticalLayout_customs.addLayout(self.horizontalLayout_top_controls)

        # 创建水平布局，包含顺序执行、循环执行等控件
        self.horizontalLayout_controls = QtWidgets.QHBoxLayout()
        self.horizontalLayout_controls.setObjectName("horizontalLayout_controls")
        
        # 添加顺序执行单选框
        self.checkBox_sequential = QtWidgets.QCheckBox(self.groupBox_customs)
        self.checkBox_sequential.setObjectName("checkBox_sequential")
        self.checkBox_sequential.setText("顺序")
        self.horizontalLayout_controls.addWidget(self.checkBox_sequential)
        
        # 添加循环执行单选框
        self.checkBox_loop = QtWidgets.QCheckBox(self.groupBox_customs)
        self.checkBox_loop.setObjectName("checkBox_loop")
        self.checkBox_loop.setText("循环")
        self.horizontalLayout_controls.addWidget(self.checkBox_loop)
        
        # 添加循环次数文本框
        self.label_loop_count = QtWidgets.QLabel(self.groupBox_customs)
        self.label_loop_count.setObjectName("label_loop_count")
        self.label_loop_count.setText("次数:")
        self.horizontalLayout_controls.addWidget(self.label_loop_count)
        
        self.lineEdit_loop_count = QtWidgets.QLineEdit(self.groupBox_customs)
        self.lineEdit_loop_count.setObjectName("lineEdit_loop_count")
        self.lineEdit_loop_count.setMaximumWidth(40)
        self.horizontalLayout_controls.addWidget(self.lineEdit_loop_count)
        
        # 添加状态显示标签
        self.label_loop_status = QtWidgets.QLabel(self.groupBox_customs)
        self.label_loop_status.setObjectName("label_loop_status")
        self.label_loop_status.setText("状态: 未运行")
        self.horizontalLayout_controls.addWidget(self.label_loop_status)
        # 将开始按钮放置到状态标签后面
        self.horizontalLayout_controls.addWidget(self.pushButton_stop_loop)

        
        # 添加弹簧
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_controls.addItem(spacerItem)
        
        # 将水平布局添加到垂直布局中
        self.verticalLayout_customs.addLayout(self.horizontalLayout_controls)
        
        # 设置表单布局（表格样式紧凑对齐）
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        # 去掉垂直间距与边距，保持列对齐
        self.formLayout_4.setVerticalSpacing(0)
        self.formLayout_4.setHorizontalSpacing(5)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_customs.addLayout(self.formLayout_4)
        
        # 将自定义按钮组设置为滚动区域的内容
        self.scrollArea.setWidget(self.groupBox_customs)
        # 创建表头标签
        self.label_43 = QtWidgets.QLabel(self.groupBox_customs)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(QtGui.QFont.Weight.Bold)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setFixedWidth(70)
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_43)
        
        # 创建右侧表头的水平布局
        headerLayout = QtWidgets.QHBoxLayout()
        headerLayout.setSpacing(5)
        headerLayout.setObjectName("headerLayout")
        headerLayout.setContentsMargins(0, 0, 0, 0)
        
        # 创建命令表头
        self.label_44 = QtWidgets.QLabel(self.groupBox_customs)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(QtGui.QFont.Weight.DemiBold)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        edit_sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        edit_sizePolicy.setHorizontalStretch(4)
        edit_sizePolicy.setVerticalStretch(0)
        self.label_44.setSizePolicy(edit_sizePolicy)
        self.label_44.setMinimumWidth(200)
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        headerLayout.addWidget(self.label_44)
        
        # 创建HEX表头
        self.label_hex_header = QtWidgets.QLabel(self.groupBox_customs)
        self.label_hex_header.setFont(font)
        self.label_hex_header.setObjectName("label_hex_header")
        self.label_hex_header.setFixedWidth(20)
        self.label_hex_header.setAlignment(QtCore.Qt.AlignCenter)
        headerLayout.addWidget(self.label_hex_header)
        
        # 创建序号表头
        self.label_seq_header = QtWidgets.QLabel(self.groupBox_customs)
        self.label_seq_header.setFont(font)
        self.label_seq_header.setObjectName("label_seq_header")
        self.label_seq_header.setFixedWidth(30)
        self.label_seq_header.setAlignment(QtCore.Qt.AlignCenter)
        headerLayout.addWidget(self.label_seq_header)
        
        # 创建延迟表头
        self.label_delay_header = QtWidgets.QLabel(self.groupBox_customs)
        self.label_delay_header.setFont(font)
        self.label_delay_header.setObjectName("label_delay_header")
        self.label_delay_header.setFixedWidth(40)
        self.label_delay_header.setAlignment(QtCore.Qt.AlignCenter)
        headerLayout.addWidget(self.label_delay_header)
        
        # 将表头布局添加到表单布局中
        self.formLayout_4.setLayout(0, QtWidgets.QFormLayout.FieldRole, headerLayout)
        self.bt_customs_send_1 = UserPushButton(self.groupBox_customs)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(QtGui.QFont.Weight.Normal)
        self.bt_customs_send_1.setFont(font)
        self.bt_customs_send_1.setObjectName("bt_customs_send_1")
        # 设置按钮文本居中和固定宽度
        self.bt_customs_send_1.setStyleSheet("text-align: center;")
        self.bt_customs_send_1.setFixedWidth(70)  # 设置按钮固定宽度
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.bt_customs_send_1)
        
        # 创建右侧控件的水平布局
        horizontalLayout1 = QtWidgets.QHBoxLayout()
        horizontalLayout1.setContentsMargins(0, 0, 0, 0)
        horizontalLayout1.setSpacing(5)
        horizontalLayout1.setObjectName("horizontalLayout_customs_1")
        
        # 创建文本框
        self.ed_customs_set_1 = QtWidgets.QLineEdit(self.groupBox_customs)
        edit_sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        edit_sizePolicy.setHorizontalStretch(2)  # 减半最小宽度
        edit_sizePolicy.setVerticalStretch(0)
        edit_sizePolicy.setHeightForWidth(self.ed_customs_set_1.sizePolicy().hasHeightForWidth())
        self.ed_customs_set_1.setSizePolicy(edit_sizePolicy)
        self.ed_customs_set_1.setMinimumWidth(200)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(QtGui.QFont.Weight.Normal)
        self.ed_customs_set_1.setFont(font)
        self.ed_customs_set_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ed_customs_set_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ed_customs_set_1.setObjectName("ed_customs_set_1")
        horizontalLayout1.addWidget(self.ed_customs_set_1)
        
        # 创建HEX单选框（使用容器确保真正居中）
        hex_container_1 = QtWidgets.QWidget(self.groupBox_customs)
        hex_container_1.setFixedWidth(20)
        hex_container_layout_1 = QtWidgets.QHBoxLayout(hex_container_1)
        hex_container_layout_1.setContentsMargins(0, 0, 0, 0)
        hex_container_layout_1.setSpacing(0)

        self.checkBox_hex_1 = QtWidgets.QCheckBox(hex_container_1)
        self.checkBox_hex_1.setObjectName("checkBox_hex_1")
        self.checkBox_hex_1.setStyleSheet("QCheckBox{margin:0;padding:0;} QCheckBox::indicator{width:16px;height:16px;}")
        self.checkBox_hex_1.setFixedSize(16, 16)
        hex_container_layout_1.addWidget(self.checkBox_hex_1, 0, QtCore.Qt.AlignCenter)
        horizontalLayout1.addWidget(hex_container_1)
        
        # 创建顺序文本框
        self.ed_customs_seq_1 = QtWidgets.QLineEdit(self.groupBox_customs)
        self.ed_customs_seq_1.setFixedWidth(30)
        self.ed_customs_seq_1.setPlaceholderText("序号")
        self.ed_customs_seq_1.setObjectName("ed_customs_seq_1")
        self.ed_customs_seq_1.setAlignment(QtCore.Qt.AlignCenter)
        horizontalLayout1.addWidget(self.ed_customs_seq_1)
        
        # 创建延迟文本框
        self.ed_customs_delay_1 = QtWidgets.QLineEdit(self.groupBox_customs)
        self.ed_customs_delay_1.setPlaceholderText("ms")
        self.ed_customs_delay_1.setObjectName("ed_customs_delay_1")
        self.ed_customs_delay_1.setFixedWidth(40)
        self.ed_customs_delay_1.setAlignment(QtCore.Qt.AlignCenter)
        horizontalLayout1.addWidget(self.ed_customs_delay_1)
        
        self.formLayout_4.setLayout(2, QtWidgets.QFormLayout.FieldRole, horizontalLayout1)
        self.bt_customs_send_2 = UserPushButton(self.groupBox_customs)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(QtGui.QFont.Weight.Normal)
        self.bt_customs_send_2.setFont(font)
        self.bt_customs_send_2.setObjectName("bt_customs_send_2")
        # 设置按钮文本居中和固定宽度
        self.bt_customs_send_2.setStyleSheet("text-align: center;")
        self.bt_customs_send_2.setFixedWidth(70)  # 设置按钮固定宽度
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.bt_customs_send_2)
        
        # 创建右侧控件的水平布局
        horizontalLayout2 = QtWidgets.QHBoxLayout()
        horizontalLayout2.setSpacing(5)
        horizontalLayout2.setContentsMargins(0, 0, 0, 0)
        horizontalLayout2.setObjectName("horizontalLayout_customs_2")
        
        # 创建文本框

        self.ed_customs_set_2 = QtWidgets.QLineEdit(self.groupBox_customs)
        edit_sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        edit_sizePolicy.setHorizontalStretch(2)  # 减半最小宽度
        edit_sizePolicy.setVerticalStretch(0)
        edit_sizePolicy.setHeightForWidth(self.ed_customs_set_2.sizePolicy().hasHeightForWidth())
        self.ed_customs_set_2.setSizePolicy(edit_sizePolicy)
        self.ed_customs_set_2.setMinimumWidth(200)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(QtGui.QFont.Weight.Normal)
        self.ed_customs_set_2.setFont(font)
        self.ed_customs_set_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ed_customs_set_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ed_customs_set_2.setObjectName("ed_customs_set_2")
        horizontalLayout2.addWidget(self.ed_customs_set_2)
        
        # 创建HEX单选框（使用容器确保真正居中）
        hex_container_2 = QtWidgets.QWidget(self.groupBox_customs)
        hex_container_2.setFixedWidth(20)
        hex_container_layout_2 = QtWidgets.QHBoxLayout(hex_container_2)
        hex_container_layout_2.setContentsMargins(0, 0, 0, 0)
        hex_container_layout_2.setSpacing(0)

        self.checkBox_hex_2 = QtWidgets.QCheckBox(hex_container_2)
        self.checkBox_hex_2.setObjectName("checkBox_hex_2")
        self.checkBox_hex_2.setStyleSheet("QCheckBox{margin:0;padding:0;} QCheckBox::indicator{width:16px;height:16px;}")
        self.checkBox_hex_2.setFixedSize(16, 16)
        hex_container_layout_2.addWidget(self.checkBox_hex_2, 0, QtCore.Qt.AlignCenter)
        horizontalLayout2.addWidget(hex_container_2)
        
        # 创建顺序文本框
        self.ed_customs_seq_2 = QtWidgets.QLineEdit(self.groupBox_customs)
        self.ed_customs_seq_2.setFixedWidth(30)
        self.ed_customs_seq_2.setPlaceholderText("序号")
        self.ed_customs_seq_2.setObjectName("ed_customs_seq_2")
        self.ed_customs_seq_2.setAlignment(QtCore.Qt.AlignCenter)
        horizontalLayout2.addWidget(self.ed_customs_seq_2)
        
        # 创建延迟文本框
        self.ed_customs_delay_2 = QtWidgets.QLineEdit(self.groupBox_customs)
        self.ed_customs_delay_2.setPlaceholderText("ms")
        self.ed_customs_delay_2.setObjectName("ed_customs_delay_2")
        self.ed_customs_delay_2.setFixedWidth(40)
        self.ed_customs_delay_2.setAlignment(QtCore.Qt.AlignCenter)
        horizontalLayout2.addWidget(self.ed_customs_delay_2)
        
        self.formLayout_4.setLayout(3, QtWidgets.QFormLayout.FieldRole, horizontalLayout2)
        # 添加辅助函数来创建自定义按钮和文本框
        def create_custom_button_and_edit(index, row):
            # 创建按钮
            button = UserPushButton(self.groupBox_customs)
            button_font = QtGui.QFont()
            button_font.setFamily("微软雅黑")
            button_font.setPointSize(9)
            button_font.setBold(False)
            button_font.setWeight(QtGui.QFont.Weight.Normal)
            button.setFont(button_font)
            button.setObjectName(f"bt_customs_send_{index}")
            # 设置按钮文本居中和固定宽度
            button.setStyleSheet("text-align: center;")
            button.setFixedWidth(70)  # 设置按钮固定宽度
            self.formLayout_4.setWidget(row, QtWidgets.QFormLayout.LabelRole, button)
            setattr(self, f"bt_customs_send_{index}", button)
            
            # 创建右侧控件的水平布局
            horizontalLayout = QtWidgets.QHBoxLayout()
            horizontalLayout.setSpacing(5)
            horizontalLayout.setContentsMargins(0, 0, 0, 0)
            horizontalLayout.setObjectName(f"horizontalLayout_customs_{index}")
            
            # 创建文本框
            edit = QtWidgets.QLineEdit(self.groupBox_customs)
            edit_sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
            edit_sizePolicy.setHorizontalStretch(2)  # 减半最小宽度
            edit_sizePolicy.setVerticalStretch(0)
            edit_sizePolicy.setHeightForWidth(edit.sizePolicy().hasHeightForWidth())
            edit.setSizePolicy(edit_sizePolicy)
            edit.setMinimumWidth(200)
            edit_font = QtGui.QFont()
            edit_font.setFamily("Consolas")
            edit_font.setPointSize(9)
            edit_font.setBold(False)
            edit_font.setWeight(QtGui.QFont.Weight.Normal)
            edit.setFont(edit_font)
            edit.setLayoutDirection(QtCore.Qt.LeftToRight)
            edit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
            edit.setObjectName(f"ed_customs_set_{index}")
            horizontalLayout.addWidget(edit)
            setattr(self, f"ed_customs_set_{index}", edit)
            
            # 创建HEX单选框（使用容器确保真正居中）
            hex_container = QtWidgets.QWidget(self.groupBox_customs)
            hex_container.setFixedWidth(20)
            hex_container_layout = QtWidgets.QHBoxLayout(hex_container)
            hex_container_layout.setContentsMargins(0, 0, 0, 0)
            hex_container_layout.setSpacing(0)

            hex_checkbox = QtWidgets.QCheckBox(hex_container)
            hex_checkbox.setObjectName(f"checkBox_hex_{index}")
            hex_checkbox.setStyleSheet("QCheckBox{margin:0;padding:0;} QCheckBox::indicator{width:16px;height:16px;}")
            hex_checkbox.setFixedSize(16, 16)
            hex_container_layout.addWidget(hex_checkbox, 0, QtCore.Qt.AlignCenter)
            horizontalLayout.addWidget(hex_container)
            setattr(self, f"checkBox_hex_{index}", hex_checkbox)
            
            # 创建顺序文本框
            seq_edit = QtWidgets.QLineEdit(self.groupBox_customs)
            seq_edit.setFixedWidth(30)
            seq_edit.setPlaceholderText("序号")
            seq_edit.setObjectName(f"ed_customs_seq_{index}")
            seq_edit.setAlignment(QtCore.Qt.AlignCenter)
            horizontalLayout.addWidget(seq_edit)
            setattr(self, f"ed_customs_seq_{index}", seq_edit)
            
            # 创建延迟文本框
            delay_edit = QtWidgets.QLineEdit(self.groupBox_customs)
            delay_edit.setPlaceholderText("ms")
            delay_edit.setObjectName(f"ed_customs_delay_{index}")
            delay_edit.setFixedWidth(40)
            delay_edit.setAlignment(QtCore.Qt.AlignCenter)
            horizontalLayout.addWidget(delay_edit)
            setattr(self, f"ed_customs_delay_{index}", delay_edit)
            
            # 将水平布局添加到表单布局中
            self.formLayout_4.setLayout(row, QtWidgets.QFormLayout.FieldRole, horizontalLayout)
            
            return button, edit
            
        # 使用for循环创建第3到第21个按钮和文本框
        for i in range(3, 100):
            button_name, edit_name = create_custom_button_and_edit(i, i + 1)
            setattr(self, f"bt_customs_send_{i}", button_name)
            setattr(self, f"ed_customs_set_{i}", edit_name)
        # 将Proto_v1添加到tab控件中
        self.tabWidget_expand.addTab(self.tab_multistring, "多字符串")
        
        # 将tab控件添加到主布局
        self.top_splitter.setStretchFactor(0, 3)
        self.top_splitter.setStretchFactor(1, 2)
        
        # 默认隐藏拓展面板tab控件
        self.tabWidget_expand.setVisible(False)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.gridLayout_2.addWidget(self.groupBox, 1, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setTitle("")
        # 取消底部控制区域边框
        self.groupBox_2.setStyleSheet("QGroupBox { border: none; }")
        self.groupBox_2.setObjectName("groupBox_2")

        # 底部区域容器（垂直排列：顶部工具行 + 内容区）
        self.verticalLayout_bottom = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_bottom.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_bottom.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_bottom.setSpacing(2)
        self.verticalLayout_bottom.setObjectName("verticalLayout_bottom")
        # 顶部工具行（左：按钮/开关；右：统计+折叠）
        self.topbar_layout = QtWidgets.QHBoxLayout()
        self.topbar_layout.setContentsMargins(0, 0, 0, 0)
        self.topbar_layout.setSpacing(2)
        self.topbar_layout.setObjectName("topbar_layout")

        # 快捷按钮栏所在行（新建一行，位于“打开串口”行上方）
        self.quickbar_row = QtWidgets.QWidget(self.groupBox_2)
        self.quickbar_row.setObjectName("quickbar_row")
        self.quickbar_layout = QtWidgets.QHBoxLayout(self.quickbar_row)
        # 减小按钮栏上下边距，降低整体高度
        self.quickbar_layout.setContentsMargins(0, 0, 0, 0)
        self.quickbar_layout.setSpacing(3)

        # 底部右侧头部：显示收发统计与折叠按钮（始终显示）
        self.bottom_header = QtWidgets.QWidget(self.groupBox_2)
        self.bottom_header.setObjectName("bottom_header")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        self.bottom_header.setSizePolicy(sizePolicy)
        self.bottom_header.setMinimumWidth(100)
        self.bottom_header.setMaximumWidth(300)
        self.bottom_header_layout = QtWidgets.QHBoxLayout(self.bottom_header)
        self.bottom_header_layout.setContentsMargins(0, 0, 0, 0)
        self.bottom_header_layout.setSpacing(4)
        self.bottom_header_layout.addStretch()
        self.label_stats = QtWidgets.QLabel(self.bottom_header)
        self.label_stats.setObjectName("label_stats")
        self.label_stats.setText("TX:0/0B (0B/s)\nRX0/0B (0B/s)")
        self.label_stats.setStyleSheet("QLabel { color: #666666; font-size: 9px; }")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        self.label_stats.setSizePolicy(sizePolicy)
        self.label_stats.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignVCenter)
        self.bottom_header_layout.addWidget(self.label_stats)
        self.bt_toggle_bottom = QtWidgets.QPushButton(self.bottom_header)
        self.bt_toggle_bottom.setObjectName("bt_toggle_bottom")
        self.bt_toggle_bottom.setMinimumSize(QtCore.QSize(24, 24))
        self.bt_toggle_bottom.setFlat(True)
        self.bottom_header_layout.addWidget(self.bt_toggle_bottom)

        # 底部内容容器：原有的串口配置与发送控制布局
        self.bottom_content_widget = QtWidgets.QWidget(self.groupBox_2)
        self.bottom_content_widget.setObjectName("bottom_content_widget")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        self.bottom_content_widget.setSizePolicy(sizePolicy)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.bottom_content_widget)
        self.horizontalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.groupBox_3 = QtWidgets.QGroupBox(self.bottom_content_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        # 移除原有的串口配置区域，这些设置现在在"更多设置"弹窗中
        # 保留groupBox_3作为占位符，但不添加任何控件
        self.groupBox_3 = QtWidgets.QGroupBox(self.bottom_content_widget)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setStyleSheet("QGroupBox { border: none; }")
        self.groupBox_3.setObjectName("groupBox_3")
        # 设置最小尺寸，避免布局问题
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_3.setMaximumSize(QtCore.QSize(0, 0))
        self.horizontalLayout_7.addWidget(self.groupBox_3)
        
        # 创建端口选择相关控件，但不在这里添加到布局中
        # 这些控件将在groupBox_4中使用
        self.label = QtWidgets.QLabel()
        self.label.setObjectName("label")
        self.comboBox_port = MyQComBox()
        self.comboBox_port.setEnabled(True)
        self.comboBox_port.setEditable(False)
        self.comboBox_port.setObjectName("comboBox_port")
        self.groupBox_5 = QtWidgets.QGroupBox(self.bottom_content_widget)
        # 发送区域容器：允许水平方向扩展，垂直方向固定
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setTitle("")
        # 取消控制区域边框
        self.groupBox_5.setStyleSheet("QGroupBox { border: none; }")
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_5)
        # 减少垂直布局的边距和间距
        self.verticalLayout_4.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_2)
        # 按钮行容器固定宽度，只占自身内容宽度
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setTitle("")
        # 取消按钮区域边框
        self.groupBox_4.setStyleSheet("QGroupBox { border: none; }")
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        # 将端口号与下拉框放置到“打开串口”按钮所在行
        self.label.setParent(self.groupBox_4)
        self.comboBox_port.setParent(self.groupBox_4)
        self.horizontalLayout_5.addWidget(self.label)
        self.horizontalLayout_5.addWidget(self.comboBox_port)
        # 添加更多设置按钮
        self.bt_more_settings = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_more_settings.sizePolicy().hasHeightForWidth())
        self.bt_more_settings.setSizePolicy(sizePolicy)
        self.bt_more_settings.setMaximumWidth(90)
        self.bt_more_settings.setObjectName("bt_more_settings")
        self.horizontalLayout_5.addWidget(self.bt_more_settings)
        self.bt_open_off_port = QtWidgets.QPushButton(self.groupBox_4)
        # 打开串口按钮固定宽度，防止水平伸缩
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_open_off_port.sizePolicy().hasHeightForWidth())
        self.bt_open_off_port.setSizePolicy(sizePolicy)
        self.bt_open_off_port.setMaximumWidth(90)
        self.bt_open_off_port.setObjectName("bt_open_off_port")
        self.horizontalLayout_5.addWidget(self.bt_open_off_port)
        self.btSaveLog = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        self.btSaveLog.setSizePolicy(sizePolicy)
        self.btSaveLog.setMaximumWidth(90)
        self.btSaveLog.setObjectName("btSaveLog")
        self.horizontalLayout_5.addWidget(self.btSaveLog)
        self.btClearLog = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        self.btClearLog.setSizePolicy(sizePolicy)
        self.btClearLog.setMaximumWidth(90)
        self.btClearLog.setObjectName("btClearLog")
        self.horizontalLayout_5.addWidget(self.btClearLog)
        self.AddButton = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        self.AddButton.setSizePolicy(sizePolicy)
        self.AddButton.setMinimumSize(QtCore.QSize(75, 0))
        self.AddButton.setMaximumWidth(90)
        self.AddButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.AddButton.setObjectName("AddButton")
        self.horizontalLayout_5.addWidget(self.AddButton)
        self.checkBox_show_add_ctrl = QtWidgets.QCheckBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        self.checkBox_show_add_ctrl.setSizePolicy(sizePolicy)
        self.checkBox_show_add_ctrl.setObjectName("checkBox_show_add_ctrl")
        self.horizontalLayout_5.addWidget(self.checkBox_show_add_ctrl)
        self.checkBox_show_hex = QtWidgets.QCheckBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        self.checkBox_show_hex.setSizePolicy(sizePolicy)
        self.checkBox_show_hex.setObjectName("checkBox_show_hex")
        self.horizontalLayout_5.addWidget(self.checkBox_show_hex)
        # 显示发送控制（在扩展面板按钮之前）
        self.checkBox_show_send = QtWidgets.QCheckBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        self.checkBox_show_send.setSizePolicy(sizePolicy)
        self.checkBox_show_send.setObjectName("checkBox_show_send")
        self.horizontalLayout_5.addWidget(self.checkBox_show_send)
        # 移除“运行模式”按钮（不再需要）
        self.bt_open_off_expand_customs = QtWidgets.QPushButton(self.groupBox_4)
        # 扩展面板按钮固定宽度，防止水平伸缩
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_open_off_expand_customs.sizePolicy().hasHeightForWidth())
        self.bt_open_off_expand_customs.setSizePolicy(sizePolicy)
        self.bt_open_off_expand_customs.setMaximumWidth(90)
        self.bt_open_off_expand_customs.setObjectName("bt_open_off_expand_customs")
        self.horizontalLayout_5.addWidget(self.bt_open_off_expand_customs)
        # 新增：快捷按钮栏显隐切换按钮（默认显示“隐藏按钮”）
        self.bt_toggle_quickbar = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        self.bt_toggle_quickbar.setSizePolicy(sizePolicy)
        self.bt_toggle_quickbar.setMaximumWidth(90)
        self.bt_toggle_quickbar.setObjectName("bt_toggle_quickbar")
        self.horizontalLayout_5.addWidget(self.bt_toggle_quickbar)
        
        # 右侧伸缩项在按钮行内不再需要统计与折叠按钮
        
        # 将按钮行加入顶部工具行（左侧）
        self.topbar_layout.addWidget(self.groupBox_4)
        # 快捷按钮栏移动到其上方独立一行
        try:
            self.quick_button_bar = QuickButtonBar(self.groupBox_2)
            qp_size = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
            self.quick_button_bar.setSizePolicy(qp_size)
            self.quickbar_layout.addWidget(self.quick_button_bar, 1)
            self.quickbar_row.setVisible(True)
        except Exception as e:
            print(f"初始化快捷按钮栏失败: {e}")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        # 减少发送区域网格布局的间距
        self.gridLayout.setContentsMargins(2, 2, 2, 2)
        self.gridLayout.setSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        # 减少水平布局间距
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit_ms_send = QtWidgets.QLineEdit(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_ms_send.sizePolicy().hasHeightForWidth())
        self.lineEdit_ms_send.setSizePolicy(sizePolicy)
        self.lineEdit_ms_send.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_ms_send.setMaximumSize(QtCore.QSize(50, 25))
        self.lineEdit_ms_send.setObjectName("lineEdit_ms_send")
        self.horizontalLayout_4.addWidget(self.lineEdit_ms_send)
        self.label_ms = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_ms.sizePolicy().hasHeightForWidth())
        self.label_ms.setSizePolicy(sizePolicy)
        self.label_ms.setObjectName("label_ms")
        self.horizontalLayout_4.addWidget(self.label_ms)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 2, 1, 1)
        self.checkBox_send_space_ctrl = QtWidgets.QCheckBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_send_space_ctrl.sizePolicy().hasHeightForWidth())
        self.checkBox_send_space_ctrl.setSizePolicy(sizePolicy)
        self.checkBox_send_space_ctrl.setChecked(True)
        self.checkBox_send_space_ctrl.setObjectName("checkBox_send_space_ctrl")
        self.gridLayout.addWidget(self.checkBox_send_space_ctrl, 1, 2, 1, 1)
        self.checkBox_send_hex = QtWidgets.QCheckBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_send_hex.sizePolicy().hasHeightForWidth())
        self.checkBox_send_hex.setSizePolicy(sizePolicy)
        self.checkBox_send_hex.setObjectName("checkBox_send_hex")
        self.gridLayout.addWidget(self.checkBox_send_hex, 0, 2, 1, 1)
        self.checkBox_timer_send = QtWidgets.QCheckBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_timer_send.sizePolicy().hasHeightForWidth())
        self.checkBox_timer_send.setSizePolicy(sizePolicy)
        self.checkBox_timer_send.setObjectName("checkBox_timer_send")
        self.gridLayout.addWidget(self.checkBox_timer_send, 2, 0, 1, 1)
        # RTS和DTR控件已移动到串口更多设置对话框中
        # 原RTS和DTR控件代码已删除
        # 创建虚拟的RTS和DTR控件以保持兼容性
        self.checkBox_rts = QtWidgets.QCheckBox()
        self.checkBox_rts.setVisible(False)  # 隐藏控件
        self.checkBox_dtr = QtWidgets.QCheckBox()
        self.checkBox_dtr.setVisible(False)  # 隐藏控件
        self.bt_send_data = QtWidgets.QPushButton(self.groupBox_5)
        self.bt_send_data.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_send_data.sizePolicy().hasHeightForWidth())
        self.bt_send_data.setSizePolicy(sizePolicy)
        self.bt_send_data.setMaximumSize(QtCore.QSize(60, 50))
        self.bt_send_data.setObjectName("bt_send_data")
        self.gridLayout.addWidget(self.bt_send_data, 0, 0, 2, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.lineEdit_send_data = SmartHexTextEdit(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_send_data.sizePolicy().hasHeightForWidth())
        self.lineEdit_send_data.setSizePolicy(sizePolicy)
        self.lineEdit_send_data.setMinimumSize(QtCore.QSize(0, 60))
        self.lineEdit_send_data.setMaximumSize(QtCore.QSize(16777215, 80))
        self.lineEdit_send_data.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lineEdit_send_data.setObjectName("lineEdit_send_data")
        # 设置自动换行
        self.lineEdit_send_data.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.horizontalLayout_2.addWidget(self.lineEdit_send_data)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_7.addWidget(self.groupBox_5)
        # 修正伸缩索引：左侧配置(索引0)固定，右侧发送区(索引1)伸缩
        self.horizontalLayout_7.setStretch(0, 0)
        self.horizontalLayout_7.setStretch(1, 1)
        # 顶部工具行：填充空白后加入右侧统计+折叠按钮
        self.topbar_layout.addStretch()
        self.topbar_layout.addWidget(self.bottom_header)
        # 添加快捷按钮行到底部区域（在顶部工具行之前）
        self.verticalLayout_bottom.addWidget(self.quickbar_row)
        # 添加顶部工具行到底部区域
        self.verticalLayout_bottom.addLayout(self.topbar_layout)
        # 添加内容区到底部区域（串口配置 + 发送区）
        self.verticalLayout_bottom.addWidget(self.bottom_content_widget)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_15.setColumnStretch(1, 1)
        self.gridLayout_13.setColumnStretch(0, 1)
        self.top_splitter.setSizes([700, 460])
        # 设置主布局的行伸缩，使上方接收区在折叠时自动扩展
        self.gridLayout_2.setRowStretch(1, 1)
        self.gridLayout_2.setRowStretch(2, 0)
        self.gridLayout_2.addWidget(self.groupBox_2, 2, 0, 1, 1)

        self.retranslateUi(Kero_Serial)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Kero_Serial)
        Kero_Serial.setTabOrder(self.tabWidget_2, self.textBrowserShow)
        Kero_Serial.setTabOrder(self.textBrowserShow, self.comboBox_port)
        Kero_Serial.setTabOrder(self.comboBox_port, self.bt_more_settings)
        Kero_Serial.setTabOrder(self.bt_more_settings, self.bt_open_off_port)
        Kero_Serial.setTabOrder(self.bt_open_off_port, self.btSaveLog)
        Kero_Serial.setTabOrder(self.btSaveLog, self.btClearLog)
        Kero_Serial.setTabOrder(self.btClearLog, self.AddButton)
        Kero_Serial.setTabOrder(self.AddButton, self.checkBox_show_add_ctrl)
        Kero_Serial.setTabOrder(self.checkBox_show_add_ctrl, self.checkBox_show_hex)
        Kero_Serial.setTabOrder(self.checkBox_show_hex, self.bt_open_off_expand_customs)
        Kero_Serial.setTabOrder(self.bt_open_off_expand_customs, self.bt_send_data)
        Kero_Serial.setTabOrder(self.bt_send_data, self.checkBox_send_hex)
        Kero_Serial.setTabOrder(self.checkBox_send_hex, self.checkBox_send_space_ctrl)
        Kero_Serial.setTabOrder(self.checkBox_send_space_ctrl, self.checkBox_timer_send)
        Kero_Serial.setTabOrder(self.checkBox_timer_send, self.lineEdit_ms_send)
        Kero_Serial.setTabOrder(self.lineEdit_ms_send, self.lineEdit_send_data)
        # 设置第一个按钮的Tab顺序（连接到前面的控件）
        Kero_Serial.setTabOrder(self.bt_customs_send_1, self.ed_customs_set_1)
        
        # 使用for循环设置其余按钮和文本框的Tab顺序
        for i in range(1, 99):
            # 从当前文本框到下一个按钮
            Kero_Serial.setTabOrder(getattr(self, f'ed_customs_set_{i}'), getattr(self, f'bt_customs_send_{i+1}'))
            # 从当前按钮到当前文本框
            if i < 98:  # 避免尝试访问bt_customs_send_100
                Kero_Serial.setTabOrder(getattr(self, f'bt_customs_send_{i+1}'), getattr(self, f'ed_customs_set_{i+1}'))
        
        # 单独设置最后一个按钮到最后一个文本框的Tab顺序
        Kero_Serial.setTabOrder(self.bt_customs_send_99, self.ed_customs_set_99)
        
        # 设置最后一个文本框的Tab顺序（连接到后面的控件）
        Kero_Serial.setTabOrder(self.ed_customs_set_99, self.Filter_Regexp)
        Kero_Serial.setTabOrder(self.Filter_Regexp, self.FilterBrowser)

    def retranslateUi(self, Kero_Serial):
        _translate = QtCore.QCoreApplication.translate
        # 窗口标题将在main.py中动态设置，包含版本号
        # Kero_Serial.setWindowTitle(_translate("Kero_Serial", "串口调试助手"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("Kero_Serial", "Main"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("Kero_Serial", "Filter"))
        
        # 设置表头文本
        self.label_43.setText(_translate("Kero_Serial", "按钮"))
        self.label_44.setText(_translate("Kero_Serial", "命令内容"))
        self.label_hex_header.setText(_translate("Kero_Serial", "H"))
        self.label_seq_header.setText(_translate("Kero_Serial", "序号"))
        self.label_delay_header.setText(_translate("Kero_Serial", "延迟"))

        self.label_43.setText(_translate("Kero_Serial", "    点击发送"))
        self.label_44.setText(_translate("Kero_Serial", "字符串"))
        # 使用for循环设置按钮文本
        for i in range(1, 100):
            getattr(self, f'bt_customs_send_{i}').setText(_translate("Kero_Serial", str(i)))

        # 顶部控制按钮文案
        self.pushButton_import_sscom.setText(_translate("Kero_Serial", "导入"))
        self.pushButton_export_sscom.setText(_translate("Kero_Serial", "导出"))

        self.label.setText(_translate("Kero_Serial", "端口号"))
        # 移除波特率、数据位、校验位、停止位的标签设置，这些现在在"更多设置"弹窗中
        self.bt_more_settings.setText(_translate("Kero_Serial", "更多设置"))
        self.bt_open_off_port.setText(_translate("Kero_Serial", "打开串口"))
        self.btSaveLog.setText(_translate("Kero_Serial", "保存接收"))
        self.btClearLog.setText(_translate("Kero_Serial", "清空接收"))
        self.AddButton.setText(_translate("Kero_Serial", "新增过滤"))
        self.CaseSensitiveCheckBox.setText(_translate("Kero_Serial", "区分大小写"))
        self.InvertModeCheckBox.setText(_translate("Kero_Serial", "反选模式"))
        self.HistoryFilterButton.setText(_translate("Kero_Serial", "历史记录筛选"))
        self.checkBox_show_add_ctrl.setText(_translate("Kero_Serial", "自动换行"))
        self.checkBox_show_hex.setText(_translate("Kero_Serial", "HEX显示"))
        # RTS和DTR控件已移动到串口更多设置对话框中
        # 运行模式按钮已移除，无需设置文本
        self.bt_open_off_expand_customs.setText(_translate("Kero_Serial", "扩展面板"))
        self.tabWidget_expand.setTabText(self.tabWidget_expand.indexOf(self.tab_multistring), _translate("Kero_Serial", "多字符串"))
        self.lineEdit_ms_send.setText(_translate("Kero_Serial", "1000"))
        self.label_ms.setText(_translate("Kero_Serial", "ms"))
        self.checkBox_send_space_ctrl.setText(_translate("Kero_Serial", "发送新行"))
        self.checkBox_send_hex.setText(_translate("Kero_Serial", "HEX发送"))
        self.checkBox_timer_send.setText(_translate("Kero_Serial", "定时发送"))
        self.bt_send_data.setText(_translate("Kero_Serial", "发送"))
        # 折叠按钮设置为空文本，使用工具提示与主逻辑中的图标
        self.bt_toggle_bottom.setText(_translate("Kero_Serial", ""))
        self.bt_toggle_bottom.setToolTip(_translate("Kero_Serial", "隐藏配置"))
        # 新增：显示发送复选框
        self.checkBox_show_send.setText(_translate("Kero_Serial", "显示发送"))
        # 新增：快捷按钮切换按钮默认文案
        self.bt_toggle_quickbar.setText(_translate("Kero_Serial", "隐藏按钮"))
from widget.MineWidget import MineWidget
from widget.MyHexQlineText import MyHexQlineText
from widget.MyQComBox import MyQComBox
from widget.MyTextBrowser import MyTextBrowser
from widget.UserPushButton import UserPushButton
from widget.QuickButtonBar import QuickButtonBar
